--
-- Inserción de registros
--

INSERT INTO LIB_BOOK_CATEGORIES
(CAT_DESCRIPCION)
VALUES
('LIBROS CIENTÍFICOS'),
('LIBROS DE AUTOAYUDA'),
('LIBROS DE AVENTURAS'),
('LIBROS DE CIENCIA FICCIÓN'),
('LIBROS DE CUENTOS'),
('LIBROS DE DEPORTE'),
('LIBROS DE HUMOR'),
('LIBROS DE LA SEGUNDA GUERRA MUNDIAL'),
('LIBROS DE SALUD'),
('NOVELA HISTÓRICA'),
('NOVELA NEGRA'),
('NOVELAS ROMÁNTICAS');

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ARTIE',
 'SPIEGELMAN',
 '1948-02-15',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('CHARLES',
 'BUKOWSKI',
 '1920-08-16',
 'M'); 
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('CARMEN',
 'POSADAS',
 '1953-08-13',
 'F');

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('PAU',
 'DONÉS',
 '1966-10-11',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('XAVIER',
 'PARMENTIER',
 '1963-12-09',
 'M');

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ROBERT',
 'KIYOSAKI',
 '1947-04-08',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('MARIANO',
 'SIGMAN',
 '1972-10-21',
 'M');

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('YUVAL NOAH',
 'HARARI',
 '1976-02-24',
 'M');
 
 INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('FRANK',
 'HERBERT',
 '1920-10-08',
 'M');
 
 INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('IGOR',
 'RYZOV',
 '1988-04-15',
 'M');
 
  INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ROI',
 'PIÑEIRO PEREZ',
 '1978-04-15',
 'M');
 
   INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JÜRGEN',
 'KLARIC',
 '1970-06-05',
 'M');

  INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ANTONIO',
 'ESCOHOTADO',
 '1941-07-05',
 'M'); 
 
  INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JESÚS',
 'CARRASCO JARAMILLO',
 '1972-07-05',
 'M');
 
   INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('RITXAR',
 'BACETE',
 '1973-07-05',
 'M');  

   INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ROBIN',
 'SHARMA',
 '1964-06-16',
 'M'); 

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JOSECHO',
 'VIZCAY',
 '1964-06-16',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JULIA',
 'NAVARRO',
 '1953-07-29',
 'F');  

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ROBERTO',
 'BOLAÑO',
 '1953-04-28',
 'M');   

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('MARK T',
 'SULLIVAN',
 '1958-06-28',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JOHN',
 'BOYNE',
 '1971-04-30',
 'M'); 
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JUAN',
 'GÓMEZ-JURADO',
 '1977-12-16',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ALBERT',
 'ESPINOSA',
 '1973-11-05',
 'M');

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ANTONIO',
 'GIL',
 '1973-11-05',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('RICHARD',
 'OSMAN',
 '1973-11-05',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ELISABET',
 'BENAVENT',
 '1984-07-03',
 'F'); 
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JAN',
 'KARSKI',
 '1967-07-03',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JOËL',
 'DICKER',
 '1967-07-03',
 'M');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('ALYSON',
 'RICHMAN',
 '1972-05-19',
 'F');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('HEATHER',
 'MORRIS',
 '1987-02-01',
 'F');
 
INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('JOSEPH',
 'JOFFO',
 '1931-04-02',
 'M');

INSERT INTO LIB_AUTHORS
(AUT_FIRST_NAME,
 AUT_LAST_NAME,
 AUT_DATE_DOB,
 AUT_GENDER)
VALUES
('MARKUS',
 'ZUSAK',
 '1975-06-23',
 'M');

INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(8,1,'9780140173154','MAUS: RELATO DE UN SUPERVIVIENTE',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(2,2,'9780062396006','LA ENFERMEDAD DE ESCRIBIR',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(3,3,'9789584292001','LA LEYENDA DE LA PEREGRINA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(4,2,'9788408193760','50 PALOS…Y SIGO SOÑANDO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(5,10,'9788425352898','EL REY DE BENGALA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(2,5,'9788433977052','FRAGMENTOS DE UN CUADERNO MANCHADO DE VINO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(6,2,'9789569582271','PADRE RICO PADRE POBRE',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(2,10,'9788433976789','EL CAPITÁN SALIÓ A COMER Y LOS MARINEROS TOMARON EL BARCO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(7,1,'9786073151528','LA VIDA SECRETA DE LA MENTE',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(8,1,'9788499926223','SAPIENS: DE ANIMALES A DIOSES',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(10,1,'8499987214','MANUAL DE NEGOCIACIÓN DEL KREMLIN',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(11,1,'9788409039470','¿ERES VACUNOFÓBICO? DIME, TE ESCUCHO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(12,1,'9789584270221','VÉNDELE A LA MENTE, NO A LA GENTE',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(13,1,'9788494862281','APRENDIENDO DE LAS DROGAS',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(14,2,'9788432237737','LLÉVAME A CASA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(15,2,'9788499426495','NUEVOS HOMBRES BUENOS. LA MASCULINIDAD EN LA ERA DEL FEMINISMO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(16,9,'9789588789460','EL MONJE QUE VENDIÓ SU FERRARI',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(17,2,'9788491112761','EL MASAJISTA DE ALMAS',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(18,3,'9789588820255','LA SANGRE DE LOS INOCENTES',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(19,3,'9789588948560','LOS DETECTIVES SALVAJES',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(20,3,'9788491292975','BAJO UN CIELO ESCARLATA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(21,3,'9788415594109 ','EL INCREÍBLE CASO DE BARNABY BROCKET',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(22,3,'9788499087085 ','CONTRATO CON DIOS',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(9,4,'9788466353779','DUNE',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(2,10,'9788433923998','AUSENCIA DEL HÉROE',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(23,10,'9788425355899','FINALES QUE MERECEN UNA HISTORIA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(24,5,'9788415448273','SEXO, DROGAS Y NBA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(25,12,'9788467060225','EL CLUB DEL CRIMEN DE LOS JUEVES',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(26,10,'9789569585692','UN CUENTO PERFECTO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(26,12,'9789585854987','EN LOS ZAPATOS DE VALERIA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(2,12,'9788433976871','SHAKESPEARE NUNCA LO HIZO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(27,8,'8492649941 ','HISTORIA DE UN ESTADO CLANDESTINO',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(28,8,'9786071135513','LOS ÚLTIMOS DÍAS DE NUESTROS PADRES',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(20,8,'9788491292975','BAJO UN CIELO ESCARLATA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(29,8,'9789563603941','LOS AMANTES DE PRAGA',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(30,8,'9789569956157','EL TATUADOR DE AUSCHWITZ',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(31,8,'9788497595681','UN SACO DE CANICAS',50000);
INSERT INTO LIB_BOOKS(BOOK_AUT_ID,BOOK_CAT_ID,BOOK_ISBN,BOOK_TITLE,BOOK_PRICE) VALUES(32,8,'9789568856144','LA LADRONA DE LIBROS',50000);